## As a business owner potentially opening a coffee shop in the Los Angeles County, what should I look out for?

In [5]:
%load_ext sql

In [6]:
%sql mysql://USERNAME:PASSWORD@HOST/DATABASE

# Data Quality Checks


## La businesses check

In [35]:
%%sql
SELECT 
    lb.id,
    COUNT(*) AS count
FROM la_businesses lb
GROUP BY lb.id;

 * mysql://admin:***@api-personal-project.clya6uswratu.us-west-1.rds.amazonaws.com/la_coffee_db?charset=utf8
1567 rows affected.


[('x0cEWLnL0iQWe6lvTwjSAQ', 1),
 ('qWJW3S3RUXyw2RVmGuZOAw', 1),
 ('elu_CU6oNbMzLIiDtNy3ww', 1),
 ('bXNni9DQruvPDPv7Vg6OxQ', 1),
 ('1daEnLjQwZoIFhUXP9r3Tw', 1),
 ('q5z2tkd_39-6gPcXRcOwng', 1),
 ('_quaKxJ2KC2kYzyhIZyiFw', 1),
 ('GpPT4axDihYRillRuEJEGw', 1),
 ('ZDBUSVK5eiozv2axmCVjnA', 1),
 ('FkmmAZYN6o3gyE3FboqPHA', 1),
 ('iKn3cdBPI9o2KNAJ4OHvLQ', 1),
 ('U7WdEDOss5y3jKbdLQBJrA', 1),
 ('HYhYc92rD7O7iIs7TmXvlg', 1),
 ('jXlGcuFRUSBxm5ycg3UQOw', 1),
 ('merpERKMMf6MpAUDYq9vZg', 1),
 ('U26db4HG0wWw1sT9mQhwoQ', 1),
 ('iAVcqTBt9e6FkyejiEnJhg', 1),
 ('vK6er0zL3MaYxE33MPwxBQ', 1),
 ('t6I8vnT6x_LVWdSDXQucgw', 1),
 ('g1qqGhzvCzxek2l0DewpPQ', 1),
 ('iC-VRLuzCVGKhLmeIk_WBA', 1),
 ('fuAL8-5XTZVao9KZyVa84w', 1),
 ('jSu3WWjjR6Jm9Qy4cpdoOA', 1),
 ('t2_SYpESmcUozlI0UrIU0A', 1),
 ('ulY53hZjCq0zstiRTp7E1Q', 1),
 ('C2u6qSLAKoVb2ujvBqarzA', 1),
 ('IyYcGfDL3oFeQ-vH7VWj6g', 1),
 ('J21yQEFIMFZjr1aSKOJzlw', 1),
 ('JZsXSvkKSRsh0B1EhmFXoQ', 1),
 ('NKrms730KRhT4FY72J6iww', 1),
 ('IBKcCJfozUg-0IwphlcCqg', 1),
 ('rR1f_EbT3JCHvTfZvQp7Tw', 1),
 ('7WU_4WoCHnYKU3a_F_H5bQ', 1),
 ('gCuDrOJPUEWDfCfGfrzKDA', 1),
 ('CWKiRHfOZKTwTklS7ybR7Q', 1),
 ('yNNtnin-2Cv-hFt077oODQ', 1),
 ('eXrUOB-VtqqP3H4MZfbnPA', 1),
 ('0fvsF6mV5DqyQJb_cc6V3Q', 1),
 ('uGHIm2xcyKMwVB2c9qmk7g', 1),
 ('fuWDAc8MP08YnZ-evy7GmA', 1),
 ('0WyRlH-fxOVLh1b3oEBEEQ', 1),
 ('xyboqr5PCRlKv99PK53Kug', 1),
 ('p74RqQjrsMuxEXGyYDwG3Q', 1),
 ('gJVz8FmYm0hJLgm6z-WnYg', 1),
 ('nEVQeJwZc0Hhf-d0sY5gBw', 1),
 ('ZxFQnp-PidPRTf23Ss_ecA', 1),
 ('pWzU4ikhUFnBC6rg9iq8_w', 1),
 ('Re-YQCm7QFt-suXx4CSlAw', 1),
 ('pviIh7uLtBVzOmWAmbfyxw', 1),
 ('KWuSIrgx9fx2m8JuqknZPA', 1),
 ('L0QlctHdsHBxPTpKevV0PA', 1),
 ('jJwBS4XIWCsRtO_kbnxJBg', 1),
 ('mufrng2MGt41KI4NYGTe6Q', 1),
 ('Vf-1OQtogTWXUnoyjazPgA', 1),
 ('gnRQ4d8RdMpr0wbhVBjEng', 1),
 ('GRcex7z3P-uGgdjFqpxYUg', 1),
 ('mELqBCzS8vRD31eiLyg_7w', 1),
 ('sfGM1J-gEWaS1QUTJ_4BzQ', 1),
 ('jFsyRPo3Y4f83vHgqWG5Jg', 1),
 ('lpDHmRmfyEynBOExfW9uNg', 1),
 ('fCfkMf27m2PcTWXLTrLM7Q', 1),
 ('sKD_FdyYZ0Y8jIYmM9p-OA', 1),
 ('Hmjw0Kz4C_-sSUi7-N2HRg', 1),
 ('U8F8bHZYQzdKCku0GBtqkA', 1),
 ('uiQ1F2s1Ls6dVIImlemM9g', 1),
 ('R1q3nXLcCxqqmg912k7Dcg', 1),
 ('z3xjbZAQG8CpBd0Pul_WGQ', 1),
 ('BqIEHiX8NNqAyGnt3_RTUg', 1),
 ('-0mw98zl4_wKPdIoEsa-CQ', 1),
 ('RGNxKOYPCA2exB2zYKqa7w', 1),
 ('8XsXR3C5k1NAXjm2-5VPKw', 1),
 ('i7dWHAj2_-aZxNOZUIY-iw', 1),
 ('wChdSuRVNKruqttN7xUXTA', 1),
 ('Qf0L601agyiGDPhqGDiaDg', 1),
 ('ZH-LGEdkmKJDAfjSxfNbKw', 1),
 ('ehKEcixcAJl7BZz8dbTMtQ', 1),
 ('eRuCZSoXwa77fxZSFmbUSA', 1),
 ('Aohc9uWSAxILFev2TwiMVQ', 1),
 ('t5h1T1PfVvz68aCuOWjxXQ', 1),
 ('-ZC3RdkKMe0AEvRdn3fNBA', 1),
 ('Emurmrl9E3vOXmiEcq3qkw', 1),
 ('qX40Yqzn-Hq-coaMoDjv-Q', 1),
 ('wtHwadHuKmCrJhBI6OGUew', 1),
 ('EfEfFksahPqRsC0iNBseKA', 1),
 ('8kj-Le5o_DSNqE9dKGWDTw', 1),
 ('hjj19yo1r_sPD9Ic-uII5w', 1),
 ('DkHP7ysDXTks2JCBBNqIaA', 1),
 ('Wz4LD7ABfwggHnICV30L6Q', 1),
 ('4gsVrBy3bVyDs2Cz-PUvxQ', 1),
 ('rpWdiTM-i4i3a3otIxoJnw', 1),
 ('hQwbv7fgQMvDmobw5ZFb2g', 1),
 ('J49iv90q2V_91SNH2BVIyA', 1),
 ('Q1ZxORzs1ChEtrjIgKVjTA', 1),
 ('FMXygWXkVK3DmOQfRij-CA', 1),
 ('tWkqjOEcoDuh5hvMdRSa7Q', 1),
 ('nozEokhAgsnfHAm5VxGN9A', 1),
 ('jv3v-cMrEAyeM2Py0apPtQ', 1),
 ('2diQcj7sFRBbcXwJ5zmnvQ', 1),
 ('x1HierOUSxuZ2NJb1cttqQ', 1),
 ('JxTtsSpsFMjTPZLbfuCG5w', 1),
 ('itfQnbflpIktTAEqg3MdTA', 1),
 ('SucE_RVNy40uYskr2WS-eg', 1),
 ('YanS-Suv11GZgnGnVIB1bQ', 1),
 ('bQVi5mgjyCiS-mr8TMjByw', 1),
 ('o70OZBMHS1wvWTyzyVcWcg', 1),
 ('I90wd2SGfFc6vmja57qpxA', 1),
 ('fwO7SDvDWiQ4yh1k2LvcyQ', 1),
 ('lW-jl8fqGQfK8MP9fR0E1w', 1),
 ('Ze4S1ladniEEQgFA3rMIKA', 1),
 ('9MnQ_xR8qAFEzVUWkPdKvA', 1),
 ('8cXUpGvn4eX_Qpd-pPYEJA', 1),
 ('v2BR5iYIMBFXexXP13UXug', 1),
 ('TwkgGnIqF9QoUg9-tZQeaA', 1),
 ('ePWI4zKo4gP_0OrNQMnAOw', 1),
 ('X37_r_UwlOoOKNuy6_0cSQ', 1),
 ('Dd9v6BA9GdJOAg-FaT-hMA', 1),
 ('PqKxehCDLo7rrbBBz7zKBQ', 1),
 ('6iXUCuMp-GVzMcS9vrM5oA', 1),
 ('8rVWoDNS6JO-5uXOD3VyXw', 1),
 ('RDRC7WyoTSuV78TAEoPQ0A', 1),
 ('bJVTVJYJL8Es0PzhBsHz8g', 1),
 ('kqgPgdIPoW1Gik8bxAGuRg', 1),
 ('iOIbvIbzqs6iVUOqP0oC5g', 1),
 ('AsIIelYWi9ms3aAjai090Q', 1),
 ('FKfygibuy4l77jyuDUoOcA', 1),


## La events check


In [36]:
%%sql
SELECT
    le.event_id,
    COUNT(*) AS count
FROM la_events le
GROUP BY le.event_id;

 * mysql://admin:***@api-personal-project.clya6uswratu.us-west-1.rds.amazonaws.com/la_coffee_db?charset=utf8
139 rows affected.


[('alhambra-official-yelp-event-holidays-at-los-amigos-mexican-grill-and-cantina', 1),
 ('arcadia-626-night-market-12', 1),
 ('arcadia-626-night-market-13', 1),
 ('arcadia-626-night-market-in-summer-2013', 1),
 ('brea-sinister-pointe-beyond-the-mirror-a-bloody-mary-tale', 1),
 ('brea-summerfest-brea-2016', 1),
 ('buena-park-cmye-yelps-pirates-dinner-adventure', 1),
 ('buena-park-knotts-boysenberry-festival', 1),
 ('buena-park-knotts-boysenberry-festival-returns-april-1-23', 1),
 ('buena-park-portos-bakery-and-cafe-buena-park-grand-opening', 1),
 ('buena-park-spring-break-food-fest-event-knotts-boysenberry-festival', 1),
 ('calabasas-tix-giveaway-nights-of-the-jack', 1),
 ('calabasas-tix-giveaway-nights-of-the-jack-a-halloween-jack-o-lantern-experience', 1),
 ('calabasas-tix-giveaway-sfcs-overnight-cinema-and-camping-dirty-dancing-30th-anniversary', 1),
 ('calabasas-yelps-fit-club-wundabar-pilates-calabasas', 1),
 ('cerritos-inihaw-uye-pinoy-potluck-3', 1),
 ('cerritos-one-more-for-the-qs-a-day-long-bbq-event-w-lechón-bacon-and-everything-else', 1),
 ('cerritos-sando-party-pinoy-potluck-take-2', 1),
 ('chatsworth-f-ck-it-its-hump-day', 1),
 ('city-of-industry-oye-k-pot-tasting', 1),
 ('compton-bbq-party-at-bludsos', 1),
 ('compton-end-of-summer-bbq-block-party-at-bludsos', 1),
 ('culver-city-yelps-passport-to-culver-city-art-walk', 1),
 ('culver-city-yelps-passport-to-culver-city-sunday-october-14th-monday-october-22nd', 1),
 ('downey-2015-downtown-downey-international-food-and-music-festival', 1),
 ('downey-2016-downtown-downey-international-food-and-music-festival', 1),
 ('fullerton-the-17th-door', 1),
 ('gardena-ramen-fair-at-marukai-gardena', 1),
 ('glendale-street-food-cinema-2018', 1),
 ('glendale-street-food-cinema-3', 1),
 ('glendale-street-food-cinema-5', 1),
 ('huntington-beach-cherry-blossom-festival-with-real-cherry-blossoms', 1),
 ('huntington-beach-huntington-beach-4th-annual-cherry-blossom-festival', 1),
 ('inglewood-tix-giveaway-corteo-by-cirque-du-soleil', 1),
 ('inglewood-tix-giveaway-golden-boy-mma-liddell-vs-ortiz-3', 1),
 ('inglewood-tix-giveaway-teen-choice-awards-2018', 1),
 ('irwindale-the-original-renaissance-pleasure-faire', 1),
 ('irwindale-the-original-renaissance-pleasure-faire-2', 1),
 ('irwindale-the-original-renaissance-pleasure-faire-2013', 1),
 ('la-canada-flintridge-descanso-garden-cherry-blossom-festival', 1),
 ('la-canada-flintridge-enchanted-forest-of-light', 1),
 ('la-canada-flintridge-enchanted-forest-of-light-at-descanso-gardens', 1),
 ('lakewood-michael-p-and-marian-bs-m-and-m-opa-opa-greek-feast-uye', 1),
 ('lawndale-hoolaulea-hawaiian-festival', 1),
 ('long-beach-baskin-robbins-31-cent-scoop-night-2', 1),
 ('long-beach-dine-out-long-beach-restaurant-week-2-0', 1),
 ('long-beach-dine-out-long-beach-restaurant-week-2017', 1),
 ('long-beach-eat-lbc-long-beach-restaurant-week-2015', 1),
 ('long-beach-list-closed-dia-de-los-yelpos-masquerade', 1),
 ('long-beach-wrong-beach-happy-hour-at-cloud-9-sports-bar', 1),
 ('long-beach-yelps-passport-party-taste-of-lbx', 1),
 ('los-angeles-atlantic-city-yelps-boardwalk-empire', 1),
 ('los-angeles-bollywood-cmye-community-manager-yelp-event-at-indias-tandoori', 1),
 ('los-angeles-california-watermelon-festival-2', 1),
 ('los-angeles-california-watermelon-festival-3', 1),
 ('los-angeles-cmye-a-taste-of-sweet-crush-2', 1),
 ('los-angeles-cmye-west-restaurant-and-lounge', 1),
 ('los-angeles-county-celebrate-asian-pacific-islander-heritage-month', 1),
 ('los-angeles-dinel-a-restaurant-week-january-18-31', 1),
 ('los-angeles-giant-toy-distribution-day-cmye', 1),
 ('los-angeles-ka-boom-uye-at-bistro-ka-happy-hour', 1),
 ('los-angeles-la-beer-week-3', 1),
 ('los-angeles-lacma-rain-room-tickets-on-sale-now', 1),
 ('los-angeles-lisa-loeb-musical-performance-and-signing', 1),
 ('los-angeles-louis-vuittons-time-capsule-exhibition', 1),
 ('los-angeles-modern-mingling-at-room-and-board', 1),
 ('los-angeles-museums-free-for-all-6', 1),
 ('los-angeles-ninongs-pastri

## La transactions check

In [37]:
%%sql
SELECT 
    lt.id,
    COUNT(*) AS count
FROM la_transactions lt
GROUP BY lt.id;

 * mysql://admin:***@api-personal-project.clya6uswratu.us-west-1.rds.amazonaws.com/la_coffee_db?charset=utf8
1567 rows affected.


[('_21BTH-EO3aCstOwdzoeAQ', 1),
 ('_3PTM3i7Okhp-LteC2synw', 1),
 ('_8gTIPvKnQequ17ECH-iKQ', 1),
 ('_8ioL82OPibDEEBbZwf97g', 1),
 ('_aGkpLlY26qosPoWlr3MDw', 1),
 ('_bz4ULYZuJJhpY4z6DYY-A', 1),
 ('_cIYfU6683HuyFq6AcGKyQ', 1),
 ('_Cop86udfkWP81q1VT_Q5A', 1),
 ('_d-OtXKHURy4VaqaMTGG-A', 1),
 ('_FAR6dVHjwYFBMOPkUeHjQ', 1),
 ('_GrodmsECI-bCUdo_cUMqA', 1),
 ('_JEjdKv-8No7TONuuXgR2A', 1),
 ('_lIIomFEZFjvTOl-c3dtow', 1),
 ('_m17RWLoKvoE1vkcu1mocA', 1),
 ('_Ns_Kw_7UrSR7OfqhJTJFg', 1),
 ('_NSj73SXOdOx1I-Ml8bHKQ', 1),
 ('_quaKxJ2KC2kYzyhIZyiFw', 1),
 ('_s8fAa3ZSxBIbj6IjUiG5Q', 1),
 ('_sla9w3jpglCnRQ7wqE_JA', 1),
 ('_UYbWDrXNsZU-hEMB5ITSw', 1),
 ('_WMeQ4PuU5yTxdwY7gdckg', 1),
 ('_xHQlmbSd7XGNSMUmEJ6JA', 1),
 ('_YHOn0thOONdMC6SaXlS0w', 1),
 ('-0mw98zl4_wKPdIoEsa-CQ', 1),
 ('-1QvxFtMgOLpSbO-oAtUgA', 1),
 ('-5zVse50VGgTqWuSxWg9Fg', 1),
 ('-9fuKQzgvyJoH9-ZGvUUYw', 1),
 ('-C2vxDphxWzYPLgNgdKJAQ', 1),
 ('-cAMvu10kcDaMgWrwmgtqg', 1),
 ('-cywUr3NriWV3IDGBHokvQ', 1),
 ('-ddx_SZ4nJJADNpl29i84g', 1),
 ('-DeSojUcgfxEG8vCqaFR3g', 1),
 ('-E62GrI-bck4XEXrFjfuWg', 1),
 ('-fMZSJaiPnpwrG_cMK-rrA', 1),
 ('-fxyNatBomw3E-__udx7ew', 1),
 ('-GfUvIuFe8FsOcCZnMKa-A', 1),
 ('-hGiuSz-X2PYS2o4f4Wvpg', 1),
 ('-HH7If5ErRtHiR6WourZwA', 1),
 ('-kIcjMwm6NdMlUZNrUdtOA', 1),
 ('-KoQb30Hphg9jRT8MGpZoA', 1),
 ('-MW0o8XruQ-suyGFrRKGsw', 1),
 ('-O3QK4mNbimjjvS94aPWxA', 1),
 ('-QbpvOsi9Rz4QeL7r-fP3A', 1),
 ('-RUhi-fMHpr7BE86hQsj8g', 1),
 ('-sy4iddjw7jeBGFB892_TQ', 1),
 ('-TQa5H5S7MRSyYjwTSpe3g', 1),
 ('-uHuiKQXW3fRZJZ1nhS0Tg', 1),
 ('-W5kx_9TFmgpYPRJUsUd0A', 1),
 ('-XJuntdsT-FsyBxFfJQpbg', 1),
 ('-ZC3RdkKMe0AEvRdn3fNBA', 1),
 ('-ZK0GNueOG-HA9xzT_7wSA', 1),
 ('-Zpel7cj2oP6ty_5vS-7-w', 1),
 ('00oKmxvpfwk1oikKnQAXDg', 1),
 ('02DP6_jh5unwapR4b9xzww', 1),
 ('02vzrkUdwJIM2C7xv4fr7g', 1),
 ('03Nz5x_OFnjyCe2A56OIXg', 1),
 ('078gF4gPF58V_Hm8LI1eUQ', 1),
 ('0fvsF6mV5DqyQJb_cc6V3Q', 1),
 ('0fydYOMuaOOjlWizHjbuIA', 1),
 ('0HJDiLQ-TIKM6VZmDApQ-Q', 1),
 ('0hkctqGnPIcHN2_fleCheg', 1),
 ('0HSn6IXxn27IpwBeUg-lpg', 1),
 ('0JMvGaeFD3be7ukF23e3qQ', 1),
 ('0MbnNM2IvNWMQ1YsPfDTjQ', 1),
 ('0nodbAAmzaG3MJWzPUpvTg', 1),
 ('0Q_0eYnAGaoNLogUl2EiSg', 1),
 ('0tvPIaFY6ijmyC_V1xLmlA', 1),
 ('0VKsa0yvPiWoVNc890INSg', 1),
 ('0VPBJRF1W62QZHeDTgoTCg', 1),
 ('0wSiC1JJuHG-aSoyYTcfqg', 1),
 ('0WSMqSaQzfUyfyHpyAj5lA', 1),
 ('0WyRlH-fxOVLh1b3oEBEEQ', 1),
 ('0Xf7Syjf2se24IKq2cp-Vg', 1),
 ('10W31qG0SoSp_8x6dfY7OQ', 1),
 ('167mf6ClOueWyKN0e_auTA', 1),
 ('16eKxRGex4mQSti1hIot9g', 1),
 ('17KteByRufcE89phZ_QIxw', 1),
 ('1AX4qwYPovubqQzlFeRyBw', 1),
 ('1bE9KkFtbq9SFDWEzA9U6A', 1),
 ('1bVE7uLrH0Nns1evIgU3uA', 1),
 ('1COPYakkKGUAZr7fk4NjSg', 1),
 ('1daEnLjQwZoIFhUXP9r3Tw', 1),
 ('1dfKRg-fQofYTNW1I2mb5Q', 1),
 ('1EV4P25hXVDB7KNJQOr9QA', 1),
 ('1FltBzT1Dir_eiW-5_XGWw', 1),
 ('1ga0LZgujvNt7dM-Tt8fOg', 1),
 ('1K_oFkr9lE_p6VmJI8sruw', 1),
 ('1k26xifgoYku7Qaudd6Z_g', 1),
 ('1KERaXCCwgfA4Bk2yivLjQ', 1),
 ('1LBrzpd7yEQoqiLba3hHuQ', 1),
 ('1TftUuLNij8G2zaB88jnSA', 1),
 ('1UDeFp5VcLN1WSqJ_Y6xpg', 1),
 ('1UEKXW7hZ2Q8KUg8pGWtdA', 1),
 ('1V4fdvliv9K8XiCgJoCsjw', 1),
 ('1W-jhPUJp1IgCokqlQHpxQ', 1),
 ('1YeA52HPSGEzOjkV3J1afA', 1),
 ('1yYxDEsr6bKEdxo6aq35zA', 1),
 ('20Q6hLAaPhngZWa3UzLqXg', 1),
 ('222LRuB5TxBNPfcVx8acFg', 1),
 ('25TCXWyE3hW3vbeKUI0Ohg', 1),
 ('29580RgN6Vva1xS6PNhO1g', 1),
 ('2A18f5TRpM9fBL29byLiAA', 1),
 ('2AknIJW625ExOSJgz8Tr4A', 1),
 ('2bC64B5-yUBo9n0taX64Jw', 1),
 ('2CIqeq15s7xhfHqtzSEshw', 1),
 ('2d36DXVBUiopW6_VrhOeJA', 1),
 ('2diQcj7sFRBbcXwJ5zmnvQ', 1),
 ('2DwtL6RcGXfPyE78_Kis9Q', 1),
 ('2dxyI5hyyB7F9bC00XnO8Q', 1),
 ('2Evhx7ph9sJNE8q34PD6dg', 1),
 ('2FyPXlPXz1yEbQWy-qJDUw', 1),
 ('2GllKrQXow-lfOphwRVLsw', 1),
 ('2HcIHeCH5scusixJcTZ3Bg', 1),
 ('2IfPYRHESCnNm-BwVTZ-Ow', 1),
 ('2jzDOv5cvbHKnTGPivIJzQ', 1),
 ('2l9leXGEP_HRlW5GI92hFQ', 1),
 ('2M7PEOQfA2JSAQt7aQ4cJQ', 1),
 ('2O-_6HRjIkOL3x_aIw2f5w', 1),
 ('2OeJysXpVghJpGdMNj3onA', 1),
 ('2owITuIx-9nLcfCidtC3Tg', 1),
 ('2qTQt-EL84PzUo3q7OMy4w', 1),
 ('2RyU6IiFxLJ7jqhHWyOG4A', 1),
 ('2s35bpMHO1BMPNJsQB_JuQ', 1),
 ('2s6p7N8skQs88BoI_I_LtA', 1),
 ('2spDfKKSwqKNd2pjSIV-vQ', 1),


## La Median Income Check

In [38]:
%%sql
SELECT 
    lmi.zipcode,
    COUNT(*) AS count
FROM la_median_income lmi
GROUP BY lmi.zipcode;

 * mysql://admin:***@api-personal-project.clya6uswratu.us-west-1.rds.amazonaws.com/la_coffee_db?charset=utf8
282 rows affected.


[(90001, 1),
 (90002, 1),
 (90003, 1),
 (90004, 1),
 (90005, 1),
 (90006, 1),
 (90007, 1),
 (90008, 1),
 (90010, 1),
 (90011, 1),
 (90012, 1),
 (90013, 1),
 (90014, 1),
 (90015, 1),
 (90016, 1),
 (90017, 1),
 (90018, 1),
 (90019, 1),
 (90020, 1),
 (90021, 1),
 (90022, 1),
 (90023, 1),
 (90024, 1),
 (90025, 1),
 (90026, 1),
 (90027, 1),
 (90028, 1),
 (90029, 1),
 (90031, 1),
 (90032, 1),
 (90033, 1),
 (90034, 1),
 (90035, 1),
 (90036, 1),
 (90037, 1),
 (90038, 1),
 (90039, 1),
 (90040, 1),
 (90041, 1),
 (90042, 1),
 (90043, 1),
 (90044, 1),
 (90045, 1),
 (90046, 1),
 (90047, 1),
 (90048, 1),
 (90049, 1),
 (90056, 1),
 (90057, 1),
 (90058, 1),
 (90059, 1),
 (90061, 1),
 (90062, 1),
 (90063, 1),
 (90064, 1),
 (90065, 1),
 (90066, 1),
 (90067, 1),
 (90068, 1),
 (90069, 1),
 (90071, 1),
 (90077, 1),
 (90094, 1),
 (90201, 1),
 (90210, 1),
 (90211, 1),
 (90212, 1),
 (90220, 1),
 (90221, 1),
 (90222, 1),
 (90230, 1),
 (90232, 1),
 (90240, 1),
 (90241, 1),
 (90242, 1),
 (90245, 1),
 (90247, 1),
 (90248, 1),
 (90249, 1),
 (90250, 1),
 (90254, 1),
 (90255, 1),
 (90260, 1),
 (90262, 1),
 (90265, 1),
 (90266, 1),
 (90270, 1),
 (90272, 1),
 (90274, 1),
 (90275, 1),
 (90277, 1),
 (90278, 1),
 (90280, 1),
 (90290, 1),
 (90291, 1),
 (90292, 1),
 (90293, 1),
 (90301, 1),
 (90302, 1),
 (90303, 1),
 (90304, 1),
 (90305, 1),
 (90401, 1),
 (90402, 1),
 (90403, 1),
 (90404, 1),
 (90405, 1),
 (90501, 1),
 (90502, 1),
 (90503, 1),
 (90504, 1),
 (90505, 1),
 (90601, 1),
 (90602, 1),
 (90603, 1),
 (90604, 1),
 (90605, 1),
 (90606, 1),
 (90631, 1),
 (90638, 1),
 (90640, 1),
 (90650, 1),
 (90660, 1),
 (90670, 1),
 (90701, 1),
 (90703, 1),
 (90704, 1),
 (90706, 1),
 (90710, 1),
 (90712, 1),
 (90713, 1),
 (90715, 1),
 (90716, 1),
 (90717, 1),
 (90723, 1),
 (90731, 1),
 (90732, 1),
 (90740, 1),
 (90744, 1),
 (90745, 1),
 (90746, 1),
 (90755, 1),
 (90802, 1),
 (90803, 1),
 (90804, 1),
 (90805, 1),
 (90806, 1),
 (90807, 1),
 (90808, 1),
 (90810, 1),
 (90813, 1),
 (90814, 1),
 (90815, 1),
 (91001, 1),
 (91006, 1),
 (91007, 1),
 (91008, 1),
 (91010, 1),
 (91011, 1),
 (91016, 1),
 (91020, 1),
 (91024, 1),
 (91030, 1),
 (91040, 1),
 (91042, 1),
 (91046, 1),
 (91101, 1),
 (91103, 1),
 (91104, 1),
 (91105, 1),
 (91106, 1),
 (91107, 1),
 (91108, 1),
 (91201, 1),
 (91202, 1),
 (91203, 1),
 (91204, 1),
 (91205, 1),
 (91206, 1),
 (91207, 1),
 (91208, 1),
 (91210, 1),
 (91214, 1),
 (91301, 1),
 (91302, 1),
 (91303, 1),
 (91304, 1),
 (91306, 1),
 (91307, 1),
 (91311, 1),
 (91316, 1),
 (91321, 1),
 (91324, 1),
 (91325, 1),
 (91326, 1),
 (91331, 1),
 (91335, 1),
 (91340, 1),
 (91342, 1),
 (91343, 1),
 (91344, 1),
 (91345, 1),
 (91350, 1),
 (91351, 1),
 (91352, 1),
 (91354, 1),
 (91355, 1),
 (91356, 1),
 (91361, 1),
 (91362, 1),
 (91364, 1),
 (91367, 1),
 (91381, 1),
 (91384, 1),
 (91387, 1),
 (91390, 1),
 (91401, 1),
 (91402, 1),
 (91403, 1),
 (91405, 1),
 (91406, 1),
 (91411, 1),
 (91423, 1),
 (91436, 1),
 (91501, 1),
 (91502, 1),
 (91504, 1),
 (91505, 1),
 (91506, 1),
 (91601, 1),
 (91602, 1),
 (91604, 1),
 (91605, 1),
 (91606, 1),
 (91607, 1),
 (91702, 1),
 (91706, 1),
 (91711, 1),
 (91722, 1),
 (91723, 1),
 (91724, 1),
 (91731, 1),
 (91732, 1),
 (91733, 1),
 (91740, 1),
 (91741, 1),
 (91744, 1),
 (91745, 1),
 (91746, 1),
 (91748, 1),
 (91750, 1),
 (91754, 1),
 (91755, 1),
 (91759, 1),
 (91765, 1),
 (91766, 1),
 (91767, 1),
 (91768, 1),
 (91770, 1),
 (91773, 1),
 (91775, 1),
 (91776, 1),
 (91780, 1),
 (91789, 1),
 (91790, 1),
 (91791, 1),
 (91792, 1),
 (91801, 1),
 (91803, 1),
 (93510, 1),
 (93532, 1),
 (93534, 1),
 (93535, 1),
 (93536, 1),
 (93543, 1),
 (93544, 1),
 (93550, 1),
 (93551, 1),
 (93552, 1),
 (93553, 1),
 (93563, 1),
 (93591, 1)]

## California Population Check


In [39]:
%%sql
SELECT
    cp.zipcode,
    COUNT(*) AS count
FROM california_population cp
GROUP BY cp.zipcode

 * mysql://admin:***@api-personal-project.clya6uswratu.us-west-1.rds.amazonaws.com/la_coffee_db?charset=utf8
1741 rows affected.


[(90011, 1),
 (91331, 1),
 (90650, 1),
 (90201, 1),
 (90044, 1),
 (92335, 1),
 (92336, 1),
 (94565, 1),
 (90250, 1),
 (90805, 1),
 (92503, 1),
 (90280, 1),
 (91342, 1),
 (91710, 1),
 (92683, 1),
 (92804, 1),
 (92154, 1),
 (92704, 1),
 (95076, 1),
 (93307, 1),
 (92376, 1),
 (91744, 1),
 (92592, 1),
 (94112, 1),
 (93033, 1),
 (93722, 1),
 (93727, 1),
 (91911, 1),
 (92126, 1),
 (92345, 1),
 (91335, 1),
 (92509, 1),
 (91709, 1),
 (94544, 1),
 (95035, 1),
 (95823, 1),
 (95630, 1),
 (93550, 1),
 (90706, 1),
 (91706, 1),
 (93257, 1),
 (92553, 1),
 (94533, 1),
 (90255, 1),
 (91910, 1),
 (94536, 1),
 (94587, 1),
 (92805, 1),
 (93535, 1),
 (93274, 1),
 (90003, 1),
 (92105, 1),
 (92882, 1),
 (91730, 1),
 (94110, 1),
 (91766, 1),
 (93306, 1),
 (91402, 1),
 (93065, 1),
 (90262, 1),
 (93536, 1),
 (92021, 1),
 (92880, 1),
 (92563, 1),
 (92703, 1),
 (90631, 1),
 (95687, 1),
 (90026, 1),
 (92114, 1),
 (95123, 1),
 (92407, 1),
 (94558, 1),
 (94509, 1),
 (90037, 1),
 (93230, 1),
 (94080, 1),
 (94538, 1),
 (90022, 1),
 (95747, 1),
 (91343, 1),
 (92801, 1),
 (92677, 1),
 (95127, 1),
 (95624, 1),
 (94541, 1),
 (95758, 1),
 (92201, 1),
 (94015, 1),
 (95020, 1),
 (91977, 1),
 (90019, 1),
 (93906, 1),
 (92115, 1),
 (94513, 1),
 (92562, 1),
 (94806, 1),
 (95206, 1),
 (92346, 1),
 (94501, 1),
 (90042, 1),
 (92627, 1),
 (90660, 1),
 (92404, 1),
 (91732, 1),
 (91950, 1),
 (90640, 1),
 (91770, 1),
 (95608, 1),
 (95112, 1),
 (92647, 1),
 (94122, 1),
 (91702, 1),
 (95014, 1),
 (95111, 1),
 (91762, 1),
 (93312, 1),
 (91761, 1),
 (92707, 1),
 (92570, 1),
 (90731, 1),
 (90004, 1),
 (93905, 1),
 (92057, 1),
 (92324, 1),
 (92504, 1),
 (95051, 1),
 (90001, 1),
 (92020, 1),
 (95355, 1),
 (90006, 1),
 (92780, 1),
 (92630, 1),
 (93291, 1),
 (90066, 1),
 (92507, 1),
 (95828, 1),
 (93117, 1),
 (93309, 1),
 (93030, 1),
 (92113, 1),
 (92392, 1),
 (90813, 1),
 (92530, 1),
 (92071, 1),
 (92571, 1),
 (94109, 1),
 (93458, 1),
 (92117, 1),
 (92708, 1),
 (90745, 1),
 (90744, 1),
 (92027, 1),
 (91764, 1),
 (94087, 1),
 (93063, 1),
 (93436, 1),
 (92130, 1),
 (95122, 1),
 (92646, 1),
 (95116, 1),
 (95376, 1),
 (94568, 1),
 (92223, 1),
 (95670, 1),
 (91405, 1),
 (93313, 1),
 (91745, 1),
 (94591, 1),
 (92701, 1),
 (94539, 1),
 (93215, 1),
 (91406, 1),
 (91801, 1),
 (92129, 1),
 (92840, 1),
 (90723, 1),
 (91304, 1),
 (92234, 1),
 (92399, 1),
 (92584, 1),
 (95350, 1),
 (91913, 1),
 (93308, 1),
 (90063, 1),
 (90034, 1),
 (91786, 1),
 (91344, 1),
 (92870, 1),
 (90018, 1),
 (95023, 1),
 (92557, 1),
 (90002, 1),
 (92505, 1),
 (95125, 1),
 (91605, 1),
 (94601, 1),
 (92025, 1),
 (95648, 1),
 (90220, 1),
 (92620, 1),
 (92833, 1),
 (92056, 1),
 (93277, 1),
 (95207, 1),
 (92656, 1),
 (95616, 1),
 (95037, 1),
 (90221, 1),
 (93003, 1),
 (90024, 1),
 (92084, 1),
 (95124, 1),
 (90047, 1),
 (92024, 1),
 (92128, 1),
 (90046, 1),
 (92691, 1),
 (92886, 1),
 (92111, 1),
 (91767, 1),
 (92626, 1),
 (93551, 1),
 (90703, 1),
 (92078, 1),
 (94086, 1),
 (92243, 1),
 (92069, 1),
 (94550, 1),
 (92026, 1),
 (90057, 1),
 (92127, 1),
 (93638, 1),
 (92544, 1),
 (92064, 1),
 (94553, 1),
 (91306, 1),
 (90638, 1),
 (90630, 1),
 (94014, 1),
 (90033, 1),
 (93304, 1),
 (93611, 1),
 (92618, 1),
 (95240, 1),
 (95351, 1),
 (90247, 1),
 (95148, 1),
 (94303, 1),
 (92028, 1),
 (92122, 1),
 (90032, 1),
 (92879, 1),
 (95336, 1),
 (95843, 1),
 (95060, 1),
 (94577, 1),
 (95136, 1),
 (94116, 1),
 (92705, 1),
 (94551, 1),
 (94560, 1),
 (92109, 1),
 (93720, 1),
 (91748, 1),
 (91352, 1),
 (90025, 1),
 (92843, 1),
 (92692, 1),
 (90023, 1),
 (92009, 1),
 (91765, 1),
 (90065, 1),
 (90620, 1),
 (95008, 1),
 (92040, 1),
 (95610, 1),
 (95307, 1),
 (92506, 1),
 (92648, 1),
 (90059, 1),
 (93455, 1),
 (93010, 1),
 (92058, 1),
 (91367, 1),
 (90016, 1),
 (94566, 1),
 (90043, 1),
 (93311, 1),
 (92236, 1),
 (91790, 1),
 (92104, 1),
 (91733, 1),
 (95403, 1),
 (92410, 1),
 (95209, 1),
 (91320, 1),
 (92688, 1),
 (90027, 1),
 (95822, 1),
 (92867, 1),
 (94117, 1),
 (93446, 1),
 (90503, 1),
 (92555, 1),
 (91789, 1),
 (94403, 1),
 (94546, 1),
 (96003, 

## Data Exploration

## Competitor Analysis, which coffee chains are the most prevalent in Los Angeles County


In [40]:
%%sql
WITH cte AS (
SELECT 
	lb.name ,
	COUNT(*) AS count
FROM la_businesses lb 
GROUP BY lb.name 
ORDER BY COUNT(*) DESC
)
SELECT 
	name,
	count,
	DENSE_RANK() OVER(ORDER BY count DESC) AS ranking
FROM cte;

 * mysql://admin:***@api-personal-project.clya6uswratu.us-west-1.rds.amazonaws.com/la_coffee_db?charset=utf8
1289 rows affected.


[('Starbucks', 59, 1),
 ('The Coffee Bean & Tea Leaf', 32, 2),
 ('Tierra Mia Coffee', 15, 3),
 ('Blue Bottle Coffee', 14, 4),
 ('Philz Coffee', 9, 5),
 ('La Monarca Bakery & Cafe', 8, 6),
 ("Peet's Coffee", 7, 7),
 ('Klatch Coffee', 7, 7),
 ('Groundwork Coffee', 6, 8),
 ('Caffe Luxxe', 6, 8),
 ('7 Leaves Cafe', 6, 8),
 ('85°C Bakery Cafe', 6, 8),
 ('Go Get Em Tiger', 5, 9),
 ('Verve Coffee Roasters', 5, 9),
 ('Bluestone Lane', 5, 9),
 ('Coffee Commissary', 5, 9),
 ('Intelligentsia Coffee', 4, 10),
 ("Porto's Bakery & Cafe", 4, 10),
 ('Sharetea', 4, 10),
 ('Macchiato', 3, 11),
 ('Drnk Coffee + Tea', 3, 11),
 ('The Boy & The Bear', 3, 11),
 ('Goodboybob Coffee Roasters', 3, 11),
 ('Stereoscope Coffee Company', 3, 11),
 ('The Pie Hole', 3, 11),
 ('Percolate', 3, 11),
 ('Sidecar Doughnuts & Coffee', 3, 11),
 ('Enigma Coffee', 3, 11),
 ('Hojas Tea House', 3, 11),
 ('Hi-Fi Espresso', 3, 11),
 ('Gong Cha', 3, 11),
 ('Bodhi Leaf Coffee Traders', 3, 11),
 ('Cafe 86', 3, 11),
 ('Paris Baguette', 3, 11),
 ('Dutch Bros Coffee', 3, 11),
 ('Casa De Cafe', 2, 12),
 ('Azucanela', 2, 12),
 ('Hilltop Coffee + Kitchen', 2, 12),
 ('Sip & Sonder', 2, 12),
 ('Cognoscenti Coffee', 2, 12),
 ('Maru Coffee', 2, 12),
 ('Constellation Coffee', 2, 12),
 ('Milkcow Cafe', 2, 12),
 ('Comoncy', 2, 12),
 ('Cafe Ruisseau', 2, 12),
 ("Menotti's Coffee Stop", 2, 12),
 ('Dayglow', 2, 12),
 ('Ideology Coffee', 2, 12),
 ('GREENDOOR Powered by Intelligentsia', 2, 12),
 ('Lo/Cal Coffee & Market', 2, 12),
 ("Zen's Tea House", 2, 12),
 ('Café de Leche', 2, 12),
 ("Tea N' Me", 2, 12),
 ('Two Guns Espresso - Manhattan Beach', 2, 12),
 ('Offset Coffee', 2, 12),
 ('The Hive', 2, 12),
 ('Cha Cha Matcha', 2, 12),
 ('Estate Coffee', 2, 12),
 ('Cafe Vida', 2, 12),
 ('La Colombe Coffee Roasters', 2, 12),
 ('Steelhead Coffee', 2, 12),
 ('Horchateria Rio Luna', 2, 12),
 ('Hiccups', 2, 12),
 ('Javatinis Espresso', 2, 12),
 ('Coffee Code', 2, 12),
 ('Solid Coffee Roasters', 2, 12),
 ('Smoking Tiger Coffee & Bread', 2, 12),
 ('Able Coffee Roasters', 2, 12),
 ('The Spot', 2, 12),
 ('Tastea', 2, 12),
 ('Colossus', 2, 12),
 ('The Mugs', 2, 12),
 ('Rose Park Roasters', 2, 12),
 ('Cassidy’s Corner Cafe', 2, 12),
 ('Highlight Coffee', 2, 12),
 ('Motto Tea Cafe', 2, 12),
 ('Nest Tea House', 2, 12),
 ('Acai Bar', 2, 12),
 ('Cafe De Olla', 2, 12),
 ('Rad Coffee', 2, 12),
 ('Miss Tea', 2, 12),
 ('5.2 Patio', 2, 12),
 ('Jones Coffee Roasters', 2, 12),
 ('Home Brewed Bar', 2, 12),
 ('Superba Snacks + Coffee', 2, 12),
 ('Le Pain Quotidien', 2, 12),
 ('Tifa Chocolate & Gelato', 2, 12),
 ('Bon Bon Tea House', 2, 12),
 ('R Coffee House', 2, 12),
 ('The Ice Bar', 2, 12),
 ('Coffee Kiosk', 2, 12),
 ('The Alley', 2, 12),
 ('3CATEA', 2, 12),
 ('Twinkle Brown Sugar', 1, 13),
 ('Coffee Del Mundo', 1, 13),
 ('El Cielito Cafe', 1, 13),
 ('Churros Y Cafe De La Holla', 1, 13),
 ('Cafe Dulce Vernon', 1, 13),
 ('Cake And Coffee House', 1, 13),
 ('Gavina Gourmet Coffee', 1, 13),
 ('The Los Angeles Banh Mi Company', 1, 13),
 ('Eatgud Cafe', 1, 13),
 ("Cruzita's Deli and Cafe", 1, 13),
 ('Watts Coffee House', 1, 13),
 ('La Monarca Bakery', 1, 13),
 ('Cafe Calle', 1, 13),
 ('Colada & Cream', 1, 13),
 ('RFRM Coffee', 1, 13),
 ("Nina's Cafe", 1, 13),
 ('milk+cookies', 1, 13),
 ('Cafe Oaxaca', 1, 13),
 ('All Saints Cafe', 1, 13),
 ('Cafe Canela', 1, 13),
 ('El Cafecito', 1, 13),
 ("Nena's Street Crepes", 1, 13),
 ('Urban Location Boba Tea House', 1, 13),
 ('Crave it', 1, 13),
 ('Dulce Vida', 1, 13),
 ('Mingles Tea Bar', 1, 13),
 ('Harun Coffee', 1, 13),
 ('Patria Coffee Roasters', 1, 13),
 ('Cafe Pruvia', 1, 13),
 ('South LA Cafe', 1, 13),
 ('Dulce', 1, 13),
 ('House Of Boba', 1, 13),
 ('Urth Caffé- Downtown LA', 1, 13),
 ('Cafe Murmurs', 1, 13),
 ('Balcony Coffee and Tea', 1, 13),
 ('Coffee Signal', 1, 13),
 ('Sweet Corner Coffee and Cakes', 1, 13),
 ('Alchemist Coffee Project', 1, 13),
 ('Alibi Coffee', 1, 13),
 ('Document Coffee Bar', 1, 13),
 ('Awesome Coffee', 1, 13),
 ('3THYME Coffee & Herbs', 1, 13),
 ('Cafe De

## Let us get a more comprehensive view on the top performing coffee shops

In [41]:
%%sql
SELECT 
	lb.name ,
	COUNT(*) AS count,
	FORMAT(AVG(lb.rating),2) AS avg_rating,
    FORMAT(AVG(lb.price),2) AS avg_price,
	SUM(lb.review_count) AS total_reviews,
	COUNT(DISTINCT lb.zip_code) operating_zipcodes
FROM la_businesses lb 
GROUP BY lb.name 
ORDER BY COUNT(*) DESC;

 * mysql://admin:***@api-personal-project.clya6uswratu.us-west-1.rds.amazonaws.com/la_coffee_db?charset=utf8
1289 rows affected.


[('Starbucks', 59, '2.62', '1.49', Decimal('8881'), 50),
 ('The Coffee Bean & Tea Leaf', 32, '3.56', '1.31', Decimal('3971'), 30),
 ('Tierra Mia Coffee', 15, '4.03', '1.60', Decimal('5526'), 15),
 ('Blue Bottle Coffee', 14, '4.04', '1.71', Decimal('2723'), 13),
 ('Philz Coffee', 9, '4.33', '1.00', Decimal('5309'), 9),
 ('La Monarca Bakery & Cafe', 8, '4.00', '1.38', Decimal('2321'), 7),
 ('Klatch Coffee', 7, '4.21', '1.14', Decimal('3274'), 7),
 ("Peet's Coffee", 7, '4.07', '1.43', Decimal('1234'), 7),
 ('7 Leaves Cafe', 6, '3.92', '1.50', Decimal('2237'), 6),
 ('85°C Bakery Cafe', 6, '3.50', '1.67', Decimal('3952'), 6),
 ('Caffe Luxxe', 6, '4.08', '1.83', Decimal('990'), 6),
 ('Groundwork Coffee', 6, '4.08', '1.33', Decimal('2143'), 5),
 ('Bluestone Lane', 5, '4.30', '0.80', Decimal('242'), 5),
 ('Coffee Commissary', 5, '3.50', '2.00', Decimal('2334'), 5),
 ('Go Get Em Tiger', 5, '3.80', '0.80', Decimal('489'), 5),
 ('Verve Coffee Roasters', 5, '4.00', '1.60', Decimal('1724'), 5),
 ('Intelligentsia Coffee', 4, '4.00', '2.00', Decimal('4915'), 4),
 ("Porto's Bakery & Cafe", 4, '4.38', '1.25', Decimal('19446'), 4),
 ('Sharetea', 4, '4.25', '1.50', Decimal('2202'), 4),
 ('Bodhi Leaf Coffee Traders', 3, '4.50', '1.33', Decimal('531'), 3),
 ('Cafe 86', 3, '4.33', '1.67', Decimal('2168'), 3),
 ('Drnk Coffee + Tea', 3, '4.00', '0.67', Decimal('172'), 3),
 ('Dutch Bros Coffee', 3, '3.83', '0.67', Decimal('74'), 3),
 ('Enigma Coffee', 3, '4.67', '1.33', Decimal('172'), 3),
 ('Gong Cha', 3, '4.00', '2.00', Decimal('506'), 3),
 ('Goodboybob Coffee Roasters', 3, '4.33', '0.67', Decimal('282'), 3),
 ('Hi-Fi Espresso', 3, '4.50', '1.00', Decimal('201'), 3),
 ('Hojas Tea House', 3, '4.17', '1.00', Decimal('1241'), 3),
 ('Macchiato', 3, '4.00', '2.00', Decimal('1475'), 3),
 ('Paris Baguette', 3, '4.17', '1.33', Decimal('794'), 3),
 ('Percolate', 3, '4.50', '1.00', Decimal('635'), 3),
 ('Sidecar Doughnuts & Coffee', 3, '4.17', '1.67', Decimal('3083'), 3),
 ('Stereoscope Coffee Company', 3, '4.67', '2.00', Decimal('847'), 3),
 ('The Boy & The Bear', 3, '4.33', '1.33', Decimal('898'), 3),
 ('The Pie Hole', 3, '4.00', '1.33', Decimal('4889'), 3),
 ('3Catea', 2, '3.75', '1.00', Decimal('321'), 2),
 ('5.2 Patio', 2, '4.25', '0.50', Decimal('242'), 2),
 ('Able Coffee Roasters', 2, '5.00', '2.00', Decimal('253'), 2),
 ('Açaí Bar', 2, '4.50', '2.00', Decimal('326'), 2),
 ('Azucanela', 2, '4.50', '1.50', Decimal('324'), 2),
 ('Bon Bon Tea House', 2, '4.50', '2.00', Decimal('2502'), 2),
 ('Café de Leche', 2, '4.25', '1.50', Decimal('699'), 2),
 ('Cafe De Olla', 2, '4.50', '2.00', Decimal('3017'), 2),
 ('Cafe Ruisseau', 2, '5.00', '2.00', Decimal('178'), 2),
 ('Cafe Vida', 2, '4.25', '2.00', Decimal('2293'), 2),
 ('Casa de Cafe', 2, '4.25', '0.50', Decimal('139'), 2),
 ('Cassidy’s Corner Cafe', 2, '4.50', '1.00', Decimal('285'), 2),
 ('Cha Cha Matcha', 2, '4.00', '2.50', Decimal('436'), 2),
 ('Coffee Code', 2, '4.25', '1.50', Decimal('1476'), 2),
 ('Coffee Kiosk', 2, '4.25', '1.00', Decimal('243'), 2),
 ('Cognoscenti Coffee', 2, '4.00', '1.50', Decimal('439'), 2),
 ('Colossus', 2, '4.50', '1.50', Decimal('272'), 2),
 ('Comoncy', 2, '4.00', '2.00', Decimal('213'), 2),
 ('Constellation Coffee', 2, '4.75', '1.50', Decimal('422'), 2),
 ('Dayglow', 2, '4.25', '1.00', Decimal('228'), 2),
 ('Estate Coffee', 2, '4.50', '0.50', Decimal('124'), 2),
 ('GREENDOOR Powered by Intelligentsia', 2, '4.25', '1.50', Decimal('1056'), 2),
 ('Hiccups', 2, '3.50', '2.00', Decimal('1849'), 2),
 ('Highlight Coffee', 2, '4.50', '1.50', Decimal('469'), 2),
 ('Hilltop Coffee + Kitchen', 2, '4.25', '1.00', Decimal('330'), 2),
 ('Home Brewed Bar', 2, '4.75', '1.00', Decimal('1058'), 2),
 ('Horchateria Rio Luna', 2, '3.75', '1.50', Decimal('2216'), 2),
 ('Ideology Coffee', 2, '4.50', '1.50', Decimal('243'), 2),
 ('Javatinis Espresso', 2, '4.25', '1.50', Decimal('601'), 2),
 ('Jones Coffee Roasters', 2, '4.00', '1.50', Decimal('960'), 2),
 ('La Colombe Coffee Roasters', 2, '4.00', '1.

## Here is a breakdown of each zip codes population, number of busiensses on yelp, their respective median income, and their population

In [42]:
%%sql
SELECT 
	lb.zip_code ,
	cp.city_name ,
    cp.population,
	SUM(lb.review_count) AS total_review_count,
	FORMAT(AVG(lb.rating) , 2) AS avg_rating,
	COUNT(le.event_id) AS daily_events_within_area,
	lmi.median_income AS median_income
FROM la_businesses lb 
JOIN california_population cp 
	ON lb.zip_code = cp.zipcode 
JOIN la_events le 
	ON cp.zipcode = le.event_zip 
JOIN la_median_income lmi 
	ON le.event_zip = lmi.zipcode 
JOIN la_transactions lt 
	ON lb.id = lt.id 
GROUP BY lb.zip_code 
ORDER BY lb.zip_code;

 * mysql://admin:***@api-personal-project.clya6uswratu.us-west-1.rds.amazonaws.com/la_coffee_db?charset=utf8
65 rows affected.


[(90001, 'Los Angeles', 59832, Decimal('990'), '3.62', 12, 43360),
 (90007, 'Los Angeles', 42433, Decimal('1968'), '4.50', 8, 27406),
 (90013, 'Los Angeles', 12559, Decimal('26150'), '4.18', 22, 22316),
 (90014, 'Los Angeles', 8688, Decimal('2562'), '4.30', 10, 40641),
 (90015, 'Los Angeles', 22651, Decimal('591'), '4.50', 7, 43890),
 (90021, 'Los Angeles', 2945, Decimal('1177'), '4.69', 8, 21635),
 (90034, 'Los Angeles', 53861, Decimal('2850'), '4.33', 6, 75714),
 (90036, 'Los Angeles', 37965, Decimal('18728'), '4.39', 36, 80539),
 (90049, 'Los Angeles', 36418, Decimal('2814'), '4.00', 18, 129688),
 (90059, 'Los Angeles', 46185, Decimal('10'), '3.50', 2, 44838),
 (90063, 'Los Angeles', 53980, Decimal('1000'), '4.80', 10, 48559),
 (90067, 'Los Angeles', 2428, Decimal('1606'), '4.00', 18, 118393),
 (90068, 'Los Angeles', 21092, Decimal('138'), '4.50', 1, 88535),
 (90071, 'Los Angeles', 126, Decimal('344'), '4.50', 2, 61875),
 (90221, 'Compton', 51688, Decimal('648'), '4.50', 6, 51377),
 (90241, 'Downey', 43215, Decimal('16268'), '4.42', 12, 72715),
 (90248, 'Gardena', 11607, Decimal('2240'), '4.00', 7, 61448),
 (90250, 'Hawthorne', 97072, Decimal('2157'), '3.56', 8, 56304),
 (90260, 'Lawndale', 34827, Decimal('286'), '4.50', 1, 65340),
 (90265, 'Malibu', 17954, Decimal('13158'), '4.05', 30, 152378),
 (90274, 'Palos Verdes Peninsula', 25061, Decimal('1424'), '4.25', 8, 169919),
 (90277, 'Redondo Beach', 34827, Decimal('3447'), '4.20', 10, 106185),
 (90280, 'South Gate', 94642, Decimal('2018'), '4.08', 12, 52321),
 (90290, 'Topanga', 5681, Decimal('2697'), '3.70', 15, 129772),
 (90291, 'Venice', 26950, Decimal('12394'), '4.12', 24, 99652),
 (90292, 'Marina Del Rey', 23549, Decimal('2589'), '4.14', 7, 114726),
 (90293, 'Playa Del Rey', 12728, Decimal('4224'), '4.00', 8, 105865),
 (90305, 'Inglewood', 15042, Decimal('2484'), '4.00', 9, 80165),
 (90401, 'Santa Monica', 7111, Decimal('27237'), '4.35', 39, 82681),
 (90503, 'Torrance', 44605, Decimal('1150'), '4.29', 14, 93063),
 (90505, 'Torrance', 37220, Decimal('7281'), '4.31', 24, 99764),
 (90601, 'Whittier', 32053, Decimal('1314'), '4.50', 8, 76732),
 (90602, 'Whittier', 25581, Decimal('320'), '4.50', 4, 55216),
 (90605, 'Whittier', 40192, Decimal('335'), '4.67', 3, 78297),
 (90640, 'Montebello', 62730, Decimal('959'), '4.58', 6, 56009),
 (90650, 'Norwalk', 105304, Decimal('1197'), '4.40', 5, 70667),
 (90670, 'Santa Fe Springs', 16700, Decimal('614'), '4.75', 4, 71343),
 (90703, 'Cerritos', 50589, Decimal('19236'), '4.40', 30, 105832),
 (90704, 'Avalon', 3979, Decimal('8624'), '3.97', 36, 73287),
 (90712, 'Lakewood', 31217, Decimal('201'), '4.50', 1, 96634),
 (90723, 'Paramount', 54513, Decimal('2520'), '3.38', 4, 55670),
 (90731, 'San Pedro', 60659, Decimal('8685'), '4.08', 36, 53456),
 (90803, 'Long Beach', 32126, Decimal('4150'), '4.14', 22, 90278),
 (90805, 'Long Beach', 95995, Decimal('168'), '4.50', 1, 50914),
 (90807, 'Long Beach', 32202, Decimal('1728'), '4.39', 9, 78948),
 (90808, 'Long Beach', 39330, Decimal('1980'), '4.31', 8, 110625),
 (91007, 'Arcadia', 34116, Decimal('4566'), '3.90', 15, 83964),
 (91011, 'La Canada Flintridge', 20301, Decimal('2580'), '4.12', 24, 175652),
 (91042, 'Tujunga', 26966, Decimal('676'), '4.17', 12, 64532),
 (91101, 'Pasadena', 21395, Decimal('11956'), '4.33', 18, 70075),
 (91103, 'Pasadena', 27659, Decimal('6766'), '4.30', 10, 71231),
 (91105, 'Pasadena', 12617, Decimal('15936'), '4.17', 27, 131158),
 (91205, 'Glendale', 37638, Decimal('2628'), '4.62', 16, 44835),
 (91302, 'Calabasas', 26712, Decimal('7200'), '4.75', 24, 133996),
 (91303, 'Canoga Park', 31586, Decimal('851'), '3.83', 3, 61250),
 (91306, 'Winnetka', 49678, Decimal('798'), '4.25', 2, 69917),
 (91311, 'Chatsworth', 40839, Decimal('634'), '4.83', 3, 91897),
 (91324, 'Northridge', 29670, Decimal('6184'), '4.43', 15, 80260),
 (91335, 'Reseda', 81824, Decimal('590'), '3.67', 3, 63748),
 (91342, 'Sylmar', 94595, Decimal('2872'), '4.00', 16, 74050),
 (91706, 'Baldwin Park', 76930, 

## Let us have a ranking system for each numeric column

In [43]:
%%sql
WITH cte AS (
SELECT 
	lb.zip_code ,
	cp.city_name ,
    FORMAT(AVG(lb.price),2) AS avg_price,
	SUM(lb.review_count) AS total_review_count,
	FORMAT(AVG(lb.rating) , 2) AS avg_rating,
	COUNT(le.event_id) AS daily_events_within_area,
	lmi.median_income AS median_income
FROM la_businesses lb 
JOIN california_population cp 
	ON lb.zip_code = cp.zipcode 
JOIN la_events le 
	ON cp.zipcode = le.event_zip 
JOIN la_median_income lmi 
	ON le.event_zip = lmi.zipcode 
JOIN la_transactions lt 
	ON lb.id = lt.id 
GROUP BY lb.zip_code 
)
SELECT 
	ROW_NUMBER() OVER() AS row_num,
	zip_code ,
	city_name,
	DENSE_RANK() OVER(ORDER BY total_review_count DESC) AS TOTAL_REVIEWS_RANKING,
	DENSE_RANK() OVER(ORDER BY avg_rating DESC) AS AVG_RATING_RANKING,
	DENSE_RANK() OVER(ORDER BY avg_price DESC) AS AVG_PRICE_RANKING,
	DENSE_RANK() OVER(ORDER BY daily_events_within_area DESC) AS EVENTS_RANKING,
	DENSE_RANK() OVER(ORDER BY median_income DESC) AS MEDIAN_INCOME_RANKING
FROM cte
GROUP BY zip_code
ORDER BY row_num;

 * mysql://admin:***@api-personal-project.clya6uswratu.us-west-1.rds.amazonaws.com/la_coffee_db?charset=utf8
65 rows affected.


[(1, 90650, 'Norwalk', 43, 11, 13, 17, 36),
 (2, 90250, 'Hawthorne', 35, 34, 6, 14, 48),
 (3, 90805, 'Long Beach', 63, 8, 1, 21, 55),
 (4, 90280, 'South Gate', 36, 24, 26, 11, 53),
 (5, 91342, 'Sylmar', 23, 27, 14, 8, 31),
 (6, 91335, 'Reseda', 57, 32, 16, 19, 42),
 (7, 91706, 'Baldwin Park', 33, 23, 27, 11, 39),
 (8, 90640, 'Montebello', 48, 7, 10, 16, 49),
 (9, 90731, 'San Pedro', 12, 24, 16, 2, 52),
 (10, 90001, 'Los Angeles', 47, 33, 29, 11, 61),
 (11, 91801, 'Alhambra', 11, 27, 21, 11, 46),
 (12, 90723, 'Paramount', 31, 36, 1, 18, 50),
 (13, 90063, 'Los Angeles', 46, 2, 27, 12, 57),
 (14, 90034, 'Los Angeles', 24, 14, 16, 16, 29),
 (15, 90221, 'Compton', 53, 8, 30, 16, 54),
 (16, 90703, 'Cerritos', 3, 11, 7, 3, 13),
 (17, 91306, 'Winnetka', 50, 18, 1, 20, 38),
 (18, 91748, 'Rowland Heights', 18, 22, 15, 10, 30),
 (19, 90059, 'Los Angeles', 65, 35, 31, 20, 58),
 (20, 91733, 'South El Monte', 51, 8, 31, 16, 56),
 (21, 90503, 'Torrance', 45, 17, 27, 10, 17),
 (22, 90241, 'Downey', 5, 10, 27, 11, 33),
 (23, 90007, 'Los Angeles', 38, 8, 14, 14, 63),
 (24, 91311, 'Chatsworth', 54, 1, 30, 19, 18),
 (25, 90605, 'Whittier', 59, 5, 30, 19, 27),
 (26, 90808, 'Long Beach', 37, 15, 28, 14, 10),
 (27, 91776, 'San Gabriel', 7, 26, 23, 3, 47),
 (28, 90036, 'Los Angeles', 4, 12, 24, 2, 23),
 (29, 91205, 'Glendale', 27, 6, 29, 8, 59),
 (30, 90505, 'Torrance', 14, 15, 20, 5, 14),
 (31, 90049, 'Los Angeles', 25, 27, 1, 7, 7),
 (32, 90277, 'Redondo Beach', 22, 19, 18, 12, 11),
 (33, 90260, 'Lawndale', 61, 8, 1, 21, 40),
 (34, 91007, 'Arcadia', 19, 29, 27, 9, 21),
 (35, 90807, 'Long Beach', 39, 12, 16, 13, 26),
 (36, 90803, 'Long Beach', 21, 22, 9, 6, 19),
 (37, 90601, 'Whittier', 42, 8, 20, 14, 28),
 (38, 91303, 'Canoga Park', 49, 30, 30, 19, 45),
 (39, 90712, 'Lakewood', 62, 8, 1, 21, 16),
 (40, 91324, 'Northridge', 17, 9, 13, 9, 24),
 (41, 91103, 'Pasadena', 16, 16, 7, 12, 35),
 (42, 91042, 'Tujunga', 52, 21, 32, 11, 41),
 (43, 90291, 'Venice', 9, 23, 10, 5, 15),
 (44, 91302, 'Calabasas', 15, 3, 21, 5, 4),
 (45, 90602, 'Whittier', 60, 8, 27, 18, 51),
 (46, 90274, 'Palos Verdes Peninsula', 41, 18, 4, 14, 2),
 (47, 90292, 'Marina Del Rey', 28, 22, 19, 15, 9),
 (48, 90015, 'Los Angeles', 56, 8, 22, 15, 60),
 (49, 91101, 'Pasadena', 10, 14, 11, 7, 37),
 (50, 90068, 'Los Angeles', 64, 8, 1, 21, 20),
 (51, 91011, 'La Canada Flintridge', 29, 23, 27, 5, 1),
 (52, 90265, 'Malibu', 8, 25, 10, 3, 3),
 (53, 90670, 'Santa Fe Springs', 55, 3, 27, 18, 34),
 (54, 90305, 'Inglewood', 32, 27, 16, 13, 25),
 (55, 90293, 'Playa Del Rey', 20, 27, 1, 14, 12),
 (56, 91105, 'Pasadena', 6, 21, 2, 4, 5),
 (57, 90013, 'Los Angeles', 2, 20, 5, 6, 64),
 (58, 90248, 'Gardena', 34, 27, 12, 15, 44),
 (59, 90014, 'Los Angeles', 30, 16, 25, 12, 62),
 (60, 90401, 'Santa Monica', 1, 13, 17, 1, 22),
 (61, 90290, 'Topanga', 26, 31, 3, 9, 6),
 (62, 90704, 'Avalon', 13, 28, 8, 2, 32),
 (63, 90021, 'Los Angeles', 44, 4, 23, 14, 65),
 (64, 90067, 'Los Angeles', 40, 27, 24, 7, 8),
 (65, 90071, 'Los Angeles', 58, 8, 10, 20, 43)]

## What is the average rating, median income?


In [44]:
%%sql
SELECT 
	FORMAT(AVG(lb.rating),2) AS avg_rating,
	FORMAT(AVG(lmi.median_income),2) AS avg_income
FROM la_businesses lb 
JOIN la_median_income lmi 
	ON lb.zip_code = lmi.zipcode ;

 * mysql://admin:***@api-personal-project.clya6uswratu.us-west-1.rds.amazonaws.com/la_coffee_db?charset=utf8
1 rows affected.


[('4.23', '80,159.75')]

##### Scenario 1: Luxury identity
- You are a prestigious coffee shop, and want to insert your business in a place with poor business ratings
- hoping to attract customers that are looking for luxury coffee experience
- rating 4.23 or below, need median income above $80,159.75

In [18]:
%%sql
WITH cte AS (
SELECT 
	lb.zip_code ,
    cp.city_name,
    AVG(lb.price) AS avg_price,
	SUM(lb.review_count) AS total_review_count,
	FORMAT(AVG(lb.rating) , 2) AS avg_rating,
	COUNT(le.event_id) AS daily_events_within_area,
	lmi.median_income AS median_income
FROM la_businesses lb 
JOIN california_population cp 
	ON lb.zip_code = cp.zipcode 
JOIN la_events le 
	ON cp.zipcode = le.event_zip 
JOIN la_median_income lmi 
	ON le.event_zip = lmi.zipcode 
JOIN la_transactions lt 
	ON lb.id = lt.id 
GROUP BY lb.zip_code 
)
SELECT 
	zip_code,
    city_name,
    avg_rating,
    FORMAT(avg_price, 2) AS avg_price,
	CASE WHEN avg_rating <= 4.23 THEN "condition met" ELSE "no" END AS rating_condition,
    median_income,
	CASE WHEN median_income >= 80159.75 THEN "condition met" ELSE "no" END AS income_condition
FROM cte
ORDER BY rating_condition, income_condition;

 * mysql://admin:***@api-personal-project.clya6uswratu.us-west-1.rds.amazonaws.com/la_coffee_db?charset=utf8
65 rows affected.


[(90292, 'Marina Del Rey', '4.14', '1.29', 'condition met', 114726, 'condition met'),
 (91105, 'Pasadena', '4.17', '1.89', 'condition met', 131158, 'condition met'),
 (90290, 'Topanga', '3.70', '1.80', 'condition met', 129772, 'condition met'),
 (90293, 'Playa Del Rey', '4.00', '2.00', 'condition met', 105865, 'condition met'),
 (90049, 'Los Angeles', '4.00', '2.00', 'condition met', 129688, 'condition met'),
 (90277, 'Redondo Beach', '4.20', '1.30', 'condition met', 106185, 'condition met'),
 (90305, 'Inglewood', '4.00', '1.33', 'condition met', 80165, 'condition met'),
 (91007, 'Arcadia', '3.90', '1.00', 'condition met', 83964, 'condition met'),
 (90803, 'Long Beach', '4.14', '1.55', 'condition met', 90278, 'condition met'),
 (90067, 'Los Angeles', '4.00', '1.11', 'condition met', 118393, 'condition met'),
 (90265, 'Malibu', '4.05', '1.50', 'condition met', 152378, 'condition met'),
 (91011, 'La Canada Flintridge', '4.12', '1.00', 'condition met', 175652, 'condition met'),
 (90291, 'Venice', '4.12', '1.50', 'condition met', 99652, 'condition met'),
 (91303, 'Canoga Park', '3.83', '0.67', 'condition met', 61250, 'no'),
 (91042, 'Tujunga', '4.17', '0.33', 'condition met', 64532, 'no'),
 (91776, 'San Gabriel', '4.03', '1.13', 'condition met', 58658, 'no'),
 (90250, 'Hawthorne', '3.56', '1.63', 'condition met', 56304, 'no'),
 (90013, 'Los Angeles', '4.18', '1.73', 'condition met', 22316, 'no'),
 (90248, 'Gardena', '4.00', '1.43', 'condition met', 61448, 'no'),
 (90731, 'San Pedro', '4.08', '1.33', 'condition met', 53456, 'no'),
 (90059, 'Los Angeles', '3.50', '0.50', 'condition met', 44838, 'no'),
 (91748, 'Rowland Heights', '4.14', '1.36', 'condition met', 74438, 'no'),
 (91706, 'Baldwin Park', '4.12', '1.00', 'condition met', 65755, 'no'),
 (90001, 'Los Angeles', '3.62', '0.75', 'condition met', 43360, 'no'),
 (90280, 'South Gate', '4.08', '1.08', 'condition met', 52321, 'no'),
 (91342, 'Sylmar', '4.00', '1.38', 'condition met', 74050, 'no'),
 (91801, 'Alhambra', '4.00', '1.17', 'condition met', 60519, 'no'),
 (90704, 'Avalon', '3.97', '1.56', 'condition met', 73287, 'no'),
 (90723, 'Paramount', '3.38', '2.00', 'condition met', 55670, 'no'),
 (91335, 'Reseda', '3.67', '1.33', 'condition met', 63748, 'no'),
 (91324, 'Northridge', '4.43', '1.40', 'no', 80260, 'condition met'),
 (90712, 'Lakewood', '4.50', '2.00', 'no', 96634, 'condition met'),
 (90503, 'Torrance', '4.29', '1.00', 'no', 93063, 'condition met'),
 (91302, 'Calabasas', '4.75', '1.17', 'no', 133996, 'condition met'),
 (90068, 'Los Angeles', '4.50', '2.00', 'no', 88535, 'condition met'),
 (90274, 'Palos Verdes Peninsula', '4.25', '1.75', 'no', 169919, 'condition met'),
 (90505, 'Torrance', '4.31', '1.25', 'no', 99764, 'condition met'),
 (90036, 'Los Angeles', '4.39', '1.11', 'no', 80539, 'condition met'),
 (90703, 'Cerritos', '4.40', '1.60', 'no', 105832, 'condition met'),
 (90808, 'Long Beach', '4.31', '0.88', 'no', 110625, 'condition met'),
 (90401, 'Santa Monica', '4.35', '1.31', 'no', 82681, 'condition met'),
 (91311, 'Chatsworth', '4.83', '0.67', 'no', 91897, 'condition met'),
 (90670, 'Santa Fe Springs', '4.75', '1.00', 'no', 71343, 'no'),
 (90021, 'Los Angeles', '4.69', '1.13', 'no', 21635, 'no'),
 (90650, 'Norwalk', '4.40', '1.40', 'no', 70667, 'no'),
 (90014, 'Los Angeles', '4.30', '1.10', 'no', 40641, 'no'),
 (90071, 'Los Angeles', '4.50', '1.50', 'no', 61875, 'no'),
 (91101, 'Pasadena', '4.33', '1.44', 'no', 70075, 'no'),
 (90007, 'Los Angeles', '4.50', '1.38', 'no', 27406, 'no'),
 (90805, 'Long Beach', '4.50', '2.00', 'no', 50914, 'no'),
 (90640, 'Montebello', '4.58', '1.50', 'no', 56009, 'no'),
 (90063, 'Los Angeles', '4.80', '1.00', 'no', 48559, 'no'),
 (90034, 'Los Angeles', '4.33', '1.33', 'no', 75714, 'no'),
 (90221, 'Compton', '4.50', '0.67', 'no', 51377, 'no'),
 (91306, 'Winnetka', '4.25', '2.00', 'no', 69917, 'no'),
 (91733, 'South El Monte', '4.50', '0.50', 'no', 50691, 'no'),
 (90241, 'Downey', '4.42', '1.00', 'no', 72715, 'no'),
 (90015, 'Los An

## What price should business owners strive for?


In [45]:
%%sql
SELECT
    avg(price) AS avg_price
FROM la_businesses;

 * mysql://admin:***@api-personal-project.clya6uswratu.us-west-1.rds.amazonaws.com/la_coffee_db?charset=utf8
1 rows affected.


[(Decimal('1.3657'),)]

## Scenario 2: Capturing market segment that allows business to take advantage of delivery

In [47]:
%%sql
SELECT 
	lb.zip_code ,
	cp.city_name ,
	COUNT(lt.id) AS unavailable
FROM la_businesses lb 
JOIN la_transactions lt 
	ON lb.id = lt.id 
JOIN california_population cp 
	ON lb.zip_code = cp.zipcode 
WHERE lt.delivery = 'not_available'
GROUP BY 1
ORDER BY COUNT(lt.id)  DESC;

 * mysql://admin:***@api-personal-project.clya6uswratu.us-west-1.rds.amazonaws.com/la_coffee_db?charset=utf8
237 rows affected.


[(90704, 'Avalon', 18),
 (90266, 'Manhattan Beach', 9),
 (90012, 'Los Angeles', 8),
 (90265, 'Malibu', 8),
 (91711, 'Claremont', 7),
 (90232, 'Culver City', 7),
 (91776, 'San Gabriel', 6),
 (90803, 'Long Beach', 6),
 (90277, 'Redondo Beach', 5),
 (90291, 'Venice', 5),
 (91740, 'Glendora', 5),
 (92397, 'Wrightwood', 5),
 (93536, 'Lancaster', 4),
 (91770, 'Rosemead', 4),
 (90744, 'Wilmington', 4),
 (91016, 'Monrovia', 4),
 (91601, 'North Hollywood', 4),
 (91340, 'San Fernando', 4),
 (91505, 'Burbank', 4),
 (91364, 'Woodland Hills', 4),
 (90717, 'Lomita', 4),
 (90254, 'Hermosa Beach', 4),
 (93510, 'Acton', 4),
 (91331, 'Pacoima', 3),
 (90706, 'Bellflower', 3),
 (90640, 'Montebello', 3),
 (91702, 'Azusa', 3),
 (90001, 'Los Angeles', 3),
 (90024, 'Los Angeles', 3),
 (90033, 'Los Angeles', 3),
 (90247, 'Gardena', 3),
 (90016, 'Los Angeles', 3),
 (93534, 'Lancaster', 3),
 (90802, 'Long Beach', 3),
 (91321, 'Newhall', 3),
 (90807, 'Long Beach', 3),
 (90028, 'Los Angeles', 3),
 (91324, 'Northridge', 3),
 (90039, 'Los Angeles', 3),
 (90405, 'Santa Monica', 3),
 (90249, 'Gardena', 3),
 (90740, 'Seal Beach', 3),
 (90404, 'Santa Monica', 3),
 (90015, 'Los Angeles', 3),
 (93560, 'Rosamond', 3),
 (90272, 'Pacific Palisades', 3),
 (90069, 'West Hollywood', 3),
 (91390, 'Santa Clarita', 3),
 (90013, 'Los Angeles', 3),
 (90094, 'Los Angeles', 3),
 (90290, 'Topanga', 3),
 (90067, 'Los Angeles', 3),
 (91210, 'Glendale', 3),
 (90280, 'South Gate', 2),
 (91342, 'Sylmar', 2),
 (91744, 'La Puente', 2),
 (93535, 'Lancaster', 2),
 (90262, 'Lynwood', 2),
 (90026, 'Los Angeles', 2),
 (90660, 'Pico Rivera', 2),
 (90731, 'San Pedro', 2),
 (93063, 'Simi Valley', 2),
 (90063, 'Los Angeles', 2),
 (90046, 'Los Angeles', 2),
 (90032, 'Los Angeles', 2),
 (91748, 'Rowland Heights', 2),
 (90059, 'Los Angeles', 2),
 (91367, 'Woodland Hills', 2),
 (91790, 'West Covina', 2),
 (91320, 'Newbury Park', 2),
 (90027, 'Los Angeles', 2),
 (90503, 'Torrance', 2),
 (91789, 'Walnut', 2),
 (91311, 'Chatsworth', 2),
 (90045, 'Los Angeles', 2),
 (90605, 'Whittier', 2),
 (90005, 'Los Angeles', 2),
 (90808, 'Long Beach', 2),
 (90804, 'Long Beach', 2),
 (90020, 'Los Angeles', 2),
 (90301, 'Inglewood', 2),
 (91205, 'Glendale', 2),
 (91362, 'Thousand Oaks', 2),
 (90049, 'Los Angeles', 2),
 (93561, 'Tehachapi', 2),
 (91773, 'San Dimas', 2),
 (91754, 'Monterey Park', 2),
 (91006, 'Arcadia', 2),
 (91604, 'Studio City', 2),
 (90601, 'Whittier', 2),
 (91214, 'La Crescenta', 2),
 (91355, 'Valencia', 2),
 (90017, 'Los Angeles', 2),
 (91504, 'Burbank', 2),
 (91302, 'Calabasas', 2),
 (91411, 'Van Nuys', 2),
 (90602, 'Whittier', 2),
 (91106, 'Pasadena', 2),
 (90403, 'Santa Monica', 2),
 (90292, 'Marina Del Rey', 2),
 (91201, 'Glendale', 2),
 (90048, 'Los Angeles', 2),
 (91101, 'Pasadena', 2),
 (91011, 'La Canada Flintridge', 2),
 (91506, 'Burbank', 2),
 (92371, 'Phelan', 2),
 (93015, 'Fillmore', 2),
 (90701, 'Artesia', 2),
 (90245, 'El Segundo', 2),
 (91208, 'Glendale', 2),
 (91108, 'San Marino', 2),
 (90248, 'Gardena', 2),
 (91024, 'Sierra Madre', 2),
 (90014, 'Los Angeles', 2),
 (91020, 'Montrose', 2),
 (90401, 'Santa Monica', 2),
 (93225, 'Frazier Park', 2),
 (90021, 'Los Angeles', 2),
 (90011, 'Los Angeles', 1),
 (90650, 'Norwalk', 1),
 (90250, 'Hawthorne', 1),
 (91710, 'Chino', 1),
 (92345, 'Hesperia', 1),
 (91709, 'Chino Hills', 1),
 (93550, 'Palmdale', 1),
 (90003, 'Los Angeles', 1),
 (91766, 'Pomona', 1),
 (91402, 'Panorama City', 1),
 (90631, 'La Habra', 1),
 (90037, 'Los Angeles', 1),
 (90022, 'Los Angeles', 1),
 (90019, 'Los Angeles', 1),
 (90042, 'Los Angeles', 1),
 (91732, 'El Monte', 1),
 (92647, 'Huntington Beach', 1),
 (90006, 'Los Angeles', 1),
 (90066, 'Los Angeles', 1),
 (91405, 'Van Nuys', 1),
 (91745, 'Hacienda Heights', 1),
 (91406, 'Van Nuys', 1),
 (91801, 'Alhambra', 1),
 (90034, 'Los Angeles', 1),
 (91344, 'Granada Hills', 1),
 (90018, 'Los Angeles', 1),
 (91605, 'North Hollywood', 1),
 (90221, 'Compton', 1),
 (91767, 'Pomona', 1),
 (93551, 'Palmdale', 1),
 (90703, 'Cer

## zipcodes and their corresponding availability in delivery and no delivery (another way to visualize)


In [48]:
%%sql
SELECT 
	lb.zip_code ,
	cp.city_name ,
	COUNT(CASE WHEN lt.delivery ='not_available' THEN lt.id ELSE NULL END) AS Count_of_deliver_unavailable,
	COUNT(CASE WHEN lt.delivery ='available' THEN lt.id ELSE NULL END) AS available
FROM la_businesses lb 
JOIN la_transactions lt 
	ON lb.id = lt.id 
JOIN california_population cp 
	ON lb.zip_code = cp.zipcode 
GROUP BY 1
ORDER BY Count_of_deliver_unavailable  DESC;


 * mysql://admin:***@api-personal-project.clya6uswratu.us-west-1.rds.amazonaws.com/la_coffee_db?charset=utf8
312 rows affected.


[(90704, 'Avalon', 18, 0),
 (90266, 'Manhattan Beach', 9, 5),
 (90012, 'Los Angeles', 8, 10),
 (90265, 'Malibu', 8, 2),
 (91711, 'Claremont', 7, 6),
 (90232, 'Culver City', 7, 11),
 (91776, 'San Gabriel', 6, 9),
 (90803, 'Long Beach', 6, 5),
 (90277, 'Redondo Beach', 5, 5),
 (90291, 'Venice', 5, 7),
 (91740, 'Glendora', 5, 4),
 (92397, 'Wrightwood', 5, 0),
 (93536, 'Lancaster', 4, 2),
 (91770, 'Rosemead', 4, 2),
 (90744, 'Wilmington', 4, 1),
 (91016, 'Monrovia', 4, 12),
 (91601, 'North Hollywood', 4, 8),
 (91340, 'San Fernando', 4, 5),
 (91505, 'Burbank', 4, 6),
 (91364, 'Woodland Hills', 4, 3),
 (90717, 'Lomita', 4, 4),
 (90254, 'Hermosa Beach', 4, 7),
 (93510, 'Acton', 4, 1),
 (91331, 'Pacoima', 3, 2),
 (90706, 'Bellflower', 3, 3),
 (90640, 'Montebello', 3, 3),
 (91702, 'Azusa', 3, 2),
 (90001, 'Los Angeles', 3, 1),
 (90024, 'Los Angeles', 3, 9),
 (90033, 'Los Angeles', 3, 3),
 (90247, 'Gardena', 3, 6),
 (90016, 'Los Angeles', 3, 3),
 (93534, 'Lancaster', 3, 5),
 (90802, 'Long Beach', 3, 7),
 (91321, 'Newhall', 3, 5),
 (90807, 'Long Beach', 3, 6),
 (90028, 'Los Angeles', 3, 6),
 (91324, 'Northridge', 3, 12),
 (90039, 'Los Angeles', 3, 5),
 (90405, 'Santa Monica', 3, 6),
 (90249, 'Gardena', 3, 4),
 (90740, 'Seal Beach', 3, 5),
 (90404, 'Santa Monica', 3, 5),
 (90015, 'Los Angeles', 3, 4),
 (93560, 'Rosamond', 3, 0),
 (90272, 'Pacific Palisades', 3, 7),
 (90069, 'West Hollywood', 3, 9),
 (91390, 'Santa Clarita', 3, 1),
 (90013, 'Los Angeles', 3, 8),
 (90094, 'Los Angeles', 3, 1),
 (90290, 'Topanga', 3, 2),
 (90067, 'Los Angeles', 3, 6),
 (91210, 'Glendale', 3, 6),
 (90280, 'South Gate', 2, 10),
 (91342, 'Sylmar', 2, 6),
 (91744, 'La Puente', 2, 1),
 (93535, 'Lancaster', 2, 1),
 (90262, 'Lynwood', 2, 4),
 (90026, 'Los Angeles', 2, 12),
 (90660, 'Pico Rivera', 2, 2),
 (90731, 'San Pedro', 2, 10),
 (93063, 'Simi Valley', 2, 1),
 (90063, 'Los Angeles', 2, 3),
 (90046, 'Los Angeles', 2, 8),
 (90032, 'Los Angeles', 2, 2),
 (91748, 'Rowland Heights', 2, 12),
 (90059, 'Los Angeles', 2, 0),
 (91367, 'Woodland Hills', 2, 3),
 (91790, 'West Covina', 2, 5),
 (91320, 'Newbury Park', 2, 2),
 (90027, 'Los Angeles', 2, 7),
 (90503, 'Torrance', 2, 5),
 (91789, 'Walnut', 2, 7),
 (91311, 'Chatsworth', 2, 1),
 (90045, 'Los Angeles', 2, 5),
 (90605, 'Whittier', 2, 1),
 (90005, 'Los Angeles', 2, 4),
 (90808, 'Long Beach', 2, 6),
 (90804, 'Long Beach', 2, 1),
 (90020, 'Los Angeles', 2, 3),
 (90301, 'Inglewood', 2, 8),
 (91205, 'Glendale', 2, 2),
 (91362, 'Thousand Oaks', 2, 7),
 (90049, 'Los Angeles', 2, 4),
 (93561, 'Tehachapi', 2, 0),
 (91773, 'San Dimas', 2, 6),
 (91754, 'Monterey Park', 2, 7),
 (91006, 'Arcadia', 2, 5),
 (91604, 'Studio City', 2, 8),
 (90601, 'Whittier', 2, 6),
 (91214, 'La Crescenta', 2, 6),
 (91355, 'Valencia', 2, 7),
 (90017, 'Los Angeles', 2, 5),
 (91504, 'Burbank', 2, 3),
 (91302, 'Calabasas', 2, 4),
 (91411, 'Van Nuys', 2, 4),
 (90602, 'Whittier', 2, 2),
 (91106, 'Pasadena', 2, 4),
 (90403, 'Santa Monica', 2, 4),
 (90292, 'Marina Del Rey', 2, 5),
 (91201, 'Glendale', 2, 5),
 (90048, 'Los Angeles', 2, 4),
 (91101, 'Pasadena', 2, 7),
 (91011, 'La Canada Flintridge', 2, 6),
 (91506, 'Burbank', 2, 3),
 (92371, 'Phelan', 2, 0),
 (93015, 'Fillmore', 2, 0),
 (90701, 'Artesia', 2, 8),
 (90245, 'El Segundo', 2, 7),
 (91208, 'Glendale', 2, 1),
 (91108, 'San Marino', 2, 0),
 (90248, 'Gardena', 2, 5),
 (91024, 'Sierra Madre', 2, 4),
 (90014, 'Los Angeles', 2, 8),
 (91020, 'Montrose', 2, 5),
 (90401, 'Santa Monica', 2, 11),
 (93225, 'Frazier Park', 2, 0),
 (90021, 'Los Angeles', 2, 6),
 (90011, 'Los Angeles', 1, 0),
 (90650, 'Norwalk', 1, 4),
 (90250, 'Hawthorne', 1, 7),
 (91710, 'Chino', 1, 5),
 (92345, 'Hesperia', 1, 1),
 (91709, 'Chino Hills', 1, 4),
 (93550, 'Palmdale', 1, 2),
 (90003, 'Los Angeles', 1, 1),
 (91766, 'Pomona', 1, 1),
 (91402, 'Panorama City', 1, 2),
 (90631, 'La Habra', 1, 2),
 (90037, 'Los Angeles', 1, 0),
 (90022, 'Los Angeles', 1, 2),
 (90019, 'Los Angeles', 1, 4),
 (90042, 'Los Angeles', 1, 11),
 (91732, 'El Mon

In [49]:
%%sql
WITH cte AS (
SELECT 
	lb.zip_code ,
	cp.city_name ,
	COUNT(CASE WHEN lt.delivery ='not_available' THEN lt.id ELSE NULL END) AS Count_of_deliver_unavailable,
	COUNT(CASE WHEN lt.delivery ='available' THEN lt.id ELSE NULL END) AS available
FROM la_businesses lb 
JOIN la_transactions lt 
	ON lb.id = lt.id 
JOIN california_population cp 
	ON lb.zip_code = cp.zipcode 
GROUP BY 1
ORDER BY Count_of_deliver_unavailable  DESC
)
SELECT 
	zip_code,
	city_name,
	FORMAT(100*Count_of_deliver_unavailable / (Count_of_deliver_unavailable + available),2) AS percentage_unavailable
FROM cte;

 * mysql://admin:***@api-personal-project.clya6uswratu.us-west-1.rds.amazonaws.com/la_coffee_db?charset=utf8
312 rows affected.


[(90704, 'Avalon', '100.00'),
 (90266, 'Manhattan Beach', '64.29'),
 (90012, 'Los Angeles', '44.44'),
 (90265, 'Malibu', '80.00'),
 (91711, 'Claremont', '53.85'),
 (90232, 'Culver City', '38.89'),
 (91776, 'San Gabriel', '40.00'),
 (90803, 'Long Beach', '54.55'),
 (90277, 'Redondo Beach', '50.00'),
 (90291, 'Venice', '41.67'),
 (91740, 'Glendora', '55.56'),
 (92397, 'Wrightwood', '100.00'),
 (93536, 'Lancaster', '66.67'),
 (91770, 'Rosemead', '66.67'),
 (90744, 'Wilmington', '80.00'),
 (91016, 'Monrovia', '25.00'),
 (91601, 'North Hollywood', '33.33'),
 (91340, 'San Fernando', '44.44'),
 (91505, 'Burbank', '40.00'),
 (91364, 'Woodland Hills', '57.14'),
 (90717, 'Lomita', '50.00'),
 (90254, 'Hermosa Beach', '36.36'),
 (93510, 'Acton', '80.00'),
 (91331, 'Pacoima', '60.00'),
 (90706, 'Bellflower', '50.00'),
 (90640, 'Montebello', '50.00'),
 (91702, 'Azusa', '60.00'),
 (90001, 'Los Angeles', '75.00'),
 (90024, 'Los Angeles', '25.00'),
 (90033, 'Los Angeles', '50.00'),
 (90247, 'Gardena', '33.33'),
 (90016, 'Los Angeles', '50.00'),
 (93534, 'Lancaster', '37.50'),
 (90802, 'Long Beach', '30.00'),
 (91321, 'Newhall', '37.50'),
 (90807, 'Long Beach', '33.33'),
 (90028, 'Los Angeles', '33.33'),
 (91324, 'Northridge', '20.00'),
 (90039, 'Los Angeles', '37.50'),
 (90405, 'Santa Monica', '33.33'),
 (90249, 'Gardena', '42.86'),
 (90740, 'Seal Beach', '37.50'),
 (90404, 'Santa Monica', '37.50'),
 (90015, 'Los Angeles', '42.86'),
 (93560, 'Rosamond', '100.00'),
 (90272, 'Pacific Palisades', '30.00'),
 (90069, 'West Hollywood', '25.00'),
 (91390, 'Santa Clarita', '75.00'),
 (90013, 'Los Angeles', '27.27'),
 (90094, 'Los Angeles', '75.00'),
 (90290, 'Topanga', '60.00'),
 (90067, 'Los Angeles', '33.33'),
 (91210, 'Glendale', '33.33'),
 (90280, 'South Gate', '16.67'),
 (91342, 'Sylmar', '25.00'),
 (91744, 'La Puente', '66.67'),
 (93535, 'Lancaster', '66.67'),
 (90262, 'Lynwood', '33.33'),
 (90026, 'Los Angeles', '14.29'),
 (90660, 'Pico Rivera', '50.00'),
 (90731, 'San Pedro', '16.67'),
 (93063, 'Simi Valley', '66.67'),
 (90063, 'Los Angeles', '40.00'),
 (90046, 'Los Angeles', '20.00'),
 (90032, 'Los Angeles', '50.00'),
 (91748, 'Rowland Heights', '14.29'),
 (90059, 'Los Angeles', '100.00'),
 (91367, 'Woodland Hills', '40.00'),
 (91790, 'West Covina', '28.57'),
 (91320, 'Newbury Park', '50.00'),
 (90027, 'Los Angeles', '22.22'),
 (90503, 'Torrance', '28.57'),
 (91789, 'Walnut', '22.22'),
 (91311, 'Chatsworth', '66.67'),
 (90045, 'Los Angeles', '28.57'),
 (90605, 'Whittier', '66.67'),
 (90005, 'Los Angeles', '33.33'),
 (90808, 'Long Beach', '25.00'),
 (90804, 'Long Beach', '66.67'),
 (90020, 'Los Angeles', '40.00'),
 (90301, 'Inglewood', '20.00'),
 (91205, 'Glendale', '50.00'),
 (91362, 'Thousand Oaks', '22.22'),
 (90049, 'Los Angeles', '33.33'),
 (93561, 'Tehachapi', '100.00'),
 (91773, 'San Dimas', '25.00'),
 (91754, 'Monterey Park', '22.22'),
 (91006, 'Arcadia', '28.57'),
 (91604, 'Studio City', '20.00'),
 (90601, 'Whittier', '25.00'),
 (91214, 'La Crescenta', '25.00'),
 (91355, 'Valencia', '22.22'),
 (90017, 'Los Angeles', '28.57'),
 (91504, 'Burbank', '40.00'),
 (91302, 'Calabasas', '33.33'),
 (91411, 'Van Nuys', '33.33'),
 (90602, 'Whittier', '50.00'),
 (91106, 'Pasadena', '33.33'),
 (90403, 'Santa Monica', '33.33'),
 (90292, 'Marina Del Rey', '28.57'),
 (91201, 'Glendale', '28.57'),
 (90048, 'Los Angeles', '33.33'),
 (91101, 'Pasadena', '22.22'),
 (91011, 'La Canada Flintridge', '25.00'),
 (91506, 'Burbank', '40.00'),
 (92371, 'Phelan', '100.00'),
 (93015, 'Fillmore', '100.00'),
 (90701, 'Artesia', '20.00'),
 (90245, 'El Segundo', '22.22'),
 (91208, 'Glendale', '66.67'),
 (91108, 'San Marino', '100.00'),
 (90248, 'Gardena', '28.57'),
 (91024, 'Sierra Madre', '33.33'),
 (90014, 'Los Angeles', '20.00'),
 (91020, 'Montrose', '28.57'),
 (90401, 'Santa Monica', '15.38'),
 (93225, 'Frazier Park', '100.00'),
 (90021, 'Los Angeles', '25.00'),
 (90011, 'Los Angeles', '100.00'),
 (90650, 'Norwalk', '20.00'),
 (90250, 'Hawthorne', '12.50'),
 (91710,